### ISSUE TITLE
Validation of inclusion return an Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by naszam** [AztecProtocol/ignition-verification#1]
Validation of inclusion of an address return the following error message:

```
Data download failed.
(node:24061) UnhandledPromiseRejectionWarning: undefined
(node:24061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by liamaharon** [comment]
me too

**Comment by ArnSch** [comment]
Sorry about that, having a look.

**Comment by ArnSch** [comment]
@liamaharon and @naszam, could you share the OS you're running this on?

**Comment by naszam** [comment]
@ArnSch Ubuntu 18.04.3 LTS

**Comment by ArnSch** [comment]
Thanks, and could you also run `sh ./scripts/g1.sh`, and share the error that you get from there (if any error)?

**Comment by pzawal** [comment]
I had the same problem, but validation worked with download scripts launched manually.

**Comment by ArnSch** [comment]
Thanks @pzawal, are you also on Ubuntu? Trying to replicate!

**Comment by pzawal** [comment]
@ArnSch: I see the error, "# /bin/bash" should be "#!/bin/bash". Works directly for me now

**Comment by ArnSch** [comment]
Yep, thanks for the spot @pzawal, that was a typo. Dash doesn't support `<<<` (didn't know!) so had to change the declaration at top of scripts to be more explicit. Have tested on Ubuntu and can confirm it works @liamaharon @naszam.

If you could pull again and let me know if you run into any other issues would be grateful!

**Comment by naszam** [comment]
> Thanks, and could you also run `sh ./scripts/g1.sh`, and share the error that you get from there (if any error)?

I've just tried that, it worked! no errors.

**Comment by naszam** [comment]
I've just tried to repeat the validation but I'm getting the following error when trying to install the python libryary py_ecc:

```
? Validating your transcript inclusion requires the python library py_ecc. Do you want to install it? Yes
Dependency install failed.
(node:9320) UnhandledPromiseRejectionWarning: undefined
(node:9320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by ArnSch** [comment]
Do you have python3 installed, along with pip3?

**Comment by naszam** [comment]
> Do you have python3 installed, along with pip3?

Yep!

**Comment by naszam** [comment]
I've tried again, I'm getting the same error.

**Comment by ArnSch** [comment]
What error do you get when running `pip3 install py_ecc`?

**Comment by naszam** [comment]
Apparently pip3 wasn't installed..
Now seems to work.
Thanks!

**Comment by naszam** [comment]
It worked perfectly!
Thanks!

**Comment by shayanb** [comment]
I get the same error on MacOSX 10.15.2 .

```
...
Data download successful.

? Validating your transcript inclusion requires the python library py_ecc. Do yo
u want to install it? Yes
Requirement already satisfied: py_ecc in .../.pyenv/versions/3.7.0/lib/python3.7/site-packages (1.4.2)


Dependency install successful.


Launching validation script...

Inclusion validation failed.
(node:49214) UnhandledPromiseRejectionWarning: undefined
(node:49214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
